### PR TITLE
51 reduce memory burden of pipeline

### PR DESCRIPTION
**Pull request by geoffwoollard**
https://github.com/flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1/issues/51

I incorporated a test validating the numerical identity of the output, so I am confident there are no errors on that side.

Before there was batch normalization and masking for all the gt maps. Since only one map is loaded in at a time, this is done on-the-fly inside the local distance computation.

### CODE REVIEW

**Review by DavidHerreros — APPROVED** [review]

**Review by DSilva27 — CHANGES_REQUESTED** [review]
I would change how the low memory stuff works, doing things in a for loop seems really unnecessary. Here is what I would do

**Comment by DSilva27** [comment]
The metrics should not care if the input is low memory or not, they should only care about volumes1, volumes2, and some arguments if necessary. The whole low memory stuff should come at the pipeline level. Here is what I would do


1. Implement functions that normalize volumes the way you want it, they should take a stack of volumes or a single volumes. Don't do this things inside an if-statement.

2. Load a chunk of the gt volumes, run all the preprocessing you need, and then get that submatrix of the full distance matrix. This should use the distance matrices you already have implemented. Populate that distance matrix on-the-fly. This way you can do a vmap to compute a submatrix, and then a simple stack operation to get the full matrix.


I would also create a low_memory_pipeline and a regular memory pipeline. All those if statements make the code very messy, and I think it'd be easy to miss something being wrong.

**Comment by geoffwoollard** [comment]
Yes, good point! I forgot that the __getitem__ takes care of indexing into sub-batches

I did the masking and normalization in the subbatch. This prevents a duplication of reading it  into memory (once for normalization / masking, another right before doing the m2m distance call)

There is still some if low memory mode control flow. To reduce code duplication.

**Comment by geoffwoollard** [comment]
Also, now the gt maps should be a .npy file, not a .pt file. 

I hope that `torch.from_numpy(np.load(fname.npy))` is not a lot slower than `torch.load(fname.pt)` for the big 160 GB file.

**Review by DSilva27 — APPROVED** [review]

**Pull request merged**
