### PR TITLE
preprocessing update and small path #39

### LINKED ISSUE #39: Remove population file being hard coded in preprocessing
There is a bug regarding the population files.

### PR DESCRIPTION
**Pull request by DSilva27**
Included a parameter for the population file in the submission config for the preprocessing pipeline. Updated the tutorial accordingly.

### CODE REVIEW

**Comment by DSilva27** [comment]
@geoffwoollard @DavidHerreros 

For some reason the test is only failing for 3.8 and 3.10, but the error the tests give me is a "key error". Not really sure why this is happening. I am also running the tests locally and they run fine.

**Comment by DSilva27** [comment]
It seems like the submission config file is different for different python versions

**Comment by DSilva27** [comment]
It was the cache, everything is fine now. I will remove some things I added to debug and push again.

**Comment by geoffwoollard** [comment]
> It was the cache, everything is fine now. I will remove some things I added to debug and push again.

That's really good to know for debugging - in case this comes up again.

**Comment by geoffwoollard** [comment]
In the notebook this wording is a bit confusing to me "keep this if you want to revert anonymity."

**Comment by geoffwoollard** [comment]
I suggest you commit the notebook with a plot shown for the projected volumes.

**Review by geoffwoollard — CHANGES_REQUESTED** [review]
See my comments 

Does the config file need to be updated, or is it the same?
https://github.com/flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1/blob/5b073772cc56e7a39d903cf56ee95c4511002398/config_files/config_preproc.yaml

**Pull request merged**
